import React, { useState } from "react";
import { signIn } from "next-auth/react";
import {
  Button,
  Container,
  PasswordInput,
  TextInput,
  Title,
} from "@mantine/core";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import { getLocationOrigin } from "next/dist/shared/lib/utils";
import Auth from "../components/Auth";
import { brandConfig } from "../config";

export default function Login() {
  const [password, setPassword] = useState("");
  const [email, setEmail] = useState("");
  return (
    <>
      <Head>
        <title>BS Games</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <main className={styles.main}>
        <Title>Sign In</Title>
        <Auth labelText="sign in"></Auth>
        <Container m={"xl"}>
          <TextInput
            label="email"
            onChange={(e: any) => setEmail(e.target.value)}
          ></TextInput>
          <PasswordInput
            label="password"
            onChange={(e: any) => setPassword(e.target.value)}
          ></PasswordInput>
          <Button
            // color="violet"
            sx={{ color: brandConfig.primaryComponentTextColor }}
            color={brandConfig.primaryComponentBackgroundColor}
            onClick={() =>
              signIn("credentials", {
                username: email,
                password: password,
                callbackUrl: getLocationOrigin(),
              })
            }
          >
            Login
          </Button>
        </Container>
      </main>
    </>
  );
}
